default: &default
  adapter: postgresql
  encoding: unicode
  username: user
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: cocoa_puffs_development

test:
  <<: *default
  database: cocoa_puffs_test